# helm install sealed-secrets sealed-secrets/sealed-secrets --version 2.20.0 -n sealed-secrets
fullnameOverride: sealed-secrets-controller
resources:
  requests: {cpu: 25m, memory: 48Mi}
  limits: {memory: 128Mi}
