---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: backup-storage
spec:
  encryptedData:
    ACCESS_KEY_ID: AgC0cfNC2qGbDNMTqUjtF6j1m/Lrd6F/WDEt1e9vOh8nSgNwtk+swd/IFlT9yAm5BvdkrJGVvs/Opzyr4SuH2uO8gvmvfcuyAi0C36szcH9qGjMcj7+bGHqiZsoC9bqOaF9afJSCj133X+n8u1OzLm1Z7/BEZsGiTU8g2p0CdaHcM1PnPkf7AL40PiMNuWcFLp494A1cuxI1tr9iaqX/O7FhgnRIwKwkHnBvfinDPmAIh8Vq7grg2MlisKfm44skGUpQFOdnuMGiZc13XISpHXvkDwWoFIoPjND6ev8fnEtl96Ts6JyUyHbg11vML6XNVMhn6vKEyRKcv8Q43kNDmvfpGgbDl4g1+QIHeFG9t3EHgzxq6x3Q4PuorTgPcHYaM7oVRyTY9yRPb/krpqvEp52uhu0o0WKQlSgu8PlizSXoQnZq68IDZ3sCxaUxwaUBu34cBZXIIJJ/bYSdK5sj8roW9lnTEl5e+Bs6iFgV7P4EF1gmRmIBnj5XmnyyW5TGKOwa1zq5pC1nRxmE8tMZAqp9i/DY2zoaHeCv4APIaDPANvQO4Z6VCiZCtNpb016z6cndpSrm3/jWMK7zeoPpO0+t4PK481+NThQXjKU0dd9TJo+ufemGywSPNC/OPlzzxKIs/Xetwq/ITHjn71/uB1EXvgMSWvNCSN7fD+58G04jtr7aX/K0O+hNo1KM/i3LDmn5nV8hdYCLhbwnXl7ogRodo4k76Q==
    ACCESS_SECRET_KEY: AgC0NnQeck06gvXAPczm/TpY1/nATzX0DE0W1xYQ36TUaK2tWLlfMnIapd5usW8JB/JG92Ci6r4thfmSM0QWI95emebdvs8qkKHRo+oN7ZXqMSuY3fCBrpUqB6BH+oKL3Pez/COeX4B72N0IXE331zQXwf1A0Dj4XVudMltKoWV8IxSp4tWvLk/JvfLZPnnDk3KExlMLrQUvmmXyNSgOLyPvFF/jXhbctX6HRVeUiido7hqjKliDpKgZDqvmojQwTHQa5kcEstEb/43P+zFZaU+n6wdNHvzJH92M2LlazhUrn798hwBe6Y6vAtG0c38xk+czjBJaXvA3cIAaHAA7Dpw5tGSKk8wuEQOUUM5a3XbF2FXXDiGI0DKn7tqPNGkJ93DdpP0VT0wYXAov7yL/DJYMs1eQdQkO90pNOwGLz4HwWdeBSmldgDzfMa0m6a3D6nycbsxEreU8fcOVseF0Ji9nNPrGVGPpFl739gZBQx5cr6aae/9KqFUdtmAXbnUQ8hrYfYst9xMpYC9QCMLP3IMHN+e91a0st1IHwdV9uSf8ilKGcrjFysSlywTQVfEDsNvAsF0UEZdPA9KTQktcX0NvhUG24r6WxMK/Z2VVh36r9PLk/VR96jOUMC3CndpC5eHRRzzt1qDPv6AtwvsoNrMUhswPm4Iq1ZUKwnncU8paIJSL6sdkuh4IAqksVqU+3RBatu9uTKf0Xmve8T121XH9GMPw2AwVoNnu3OHsUEv6or49YwQtBqla
  template:
    metadata:
      name: s3-credentials
      namespace: backup-storage
    type: Opaque
