---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: ledger
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBD7nquG5LhyB0va5K2flL1IT1d80/b/2kcrR+E/7ghGlbeQTjtcqz5FMRBlW/1YzV5fQCYqYdnGzLy3OX4STBndciFC7cTG9Lk2oPdM0qVLPfp3ifYHD+GqtL8iMWb09LeAY/WEzb6xaNPLHyCfAmh53GNzhgs3jV5UgNaSGPO/bR6LuS+u/wjWYuALhwXBh6CQs3Wh+YS/Kw75YTnPSwlm77UvSSys3P6X2+yGAi0CDRHZLlTGCsL1cIPEcwainxLnZdsxH2sb7OSoHAOd70unMYHSZl0q0b9UGAaWpOQCGpP6l13En/PwJ9vTST1LhN6n7epuX9dqI6jb60yt7u+gvMlPeuJpE1Y6xrWjSdvSZF+q4++hi+RzbUGK/qAZAysc99TMfrGqocyDFbzP86013DGrnEejboZufkXhRkNBJ4gKkW4ZMzw8sXRfYSXDJlu/qLhMiNB+5MET2yHnPHooqxcLMe5RiRsEdB++mnGCQcOGM/tvq6r2Pk/k5aACStHbBUYDZ8PTPfXcevr9ZKD+pNf3POHupmwrCwQy2fvEqcYXL3Or1iboA3uOlTxakDYcA6vaipMcab+DD8e2bTKNlcqu3vXHZWXlanyvjhlrtoVitQEMZ/p5jrARY/mg6kt7+DNYucb1xv2KBR6sZqUh1p90j+n9hoplyHi72xMr4MdqEy9/z7D9uu/S6DnHM3QtDUBZcT5CTd8ZG5eHDspQNLKOA==
    ACCESS_SECRET_KEY: AgCBDj9bbDZDX7dI63rqgvpsfem+ELzw7BPYWXRchEynYAqry/RXdxKgBVmEx67z7M48POhRLr8NROuAb8FHUrug5m68AQivjyEGR4MKGOdLeewcAYr2WOKHNqUbGNx/KavCv+LwXK3Apq7KyStXX2IT5KkV8U8KmLDZcUF0srF+HuURAMSJkY/9HL2eeYG/bNHkMAwwumi9Hdzm6yU2sR1WBPmjT+Cyi343Vq/OGibbbtOccBv6l1BLTmZdE77ZNZYqOTls+jKnqMIvK64Oxfjf8mc4i4bu3TOu6smE0IJnoNsNCSDtXHrynYK/d5KqY1f4nYanUUSId+4QAb9bL2A9i7lpS0TykZWt9qxEu+UalxSXOVR2MRrF0khF7g1tyfKNNagLUuCe9LBRDGuA/aGoZTlcD+p78OvhHnvhVW6I51pMZ12n8kKnAqn9TdAH+UOp5T4ChqfJISSPm08qLrJ/B6Vl7+pt5MBd5KCTUuqSnGk3LqQQjGDtPDT24plIcOFGQkZB9q07RzhhwUoLtZ5H5yGoFJ+74rBPhYbPsaI9RMhnpYifNLKg7MgyI6BFHOD2PiwMYsvbmgcRG1Ww03bI2t8SXSficGKQRH37dT/bEr0lCnmqRBTK4KSfYYeeYZFKoLJSc3n7Axrcfwda+EXo583uAtpESG7UOLbX3uU9f1BB1Ap5mMSODc2e97Rxe7xXXYV2OsiEvVraOlB7sZ7E9xhiKNhBRCGxmRIqI/8sHFKS8LmW1GmE
  template:
    metadata:
      name: s3-credentials
      namespace: ledger
    type: Opaque
