---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC1MSaeofeIS0d/6ZLx2eS8EQLN/lHyBEvaKkDmSZ7RRc6tvxi0xSg/JQx2vSMGtWwRyVIXqVFwFitL5ZjWODpFxoFquokZ/qOL07HZCWWssx0j70LrFxf37FY6wQ2qcGzr66xBJVMcZYRtyThfiRSaq0+o2mjdDcFc8Y5702RgeY2OMsAtQ5KUJMWnEk2cvZ6/f87SU9NYmDDjznBAm7hIFFZf2AoUruE9s4yv2xEynQ3AgpqgoHnv26VxTU7m/KW3I8aVshjChDXIG1mllzRPnXPrxrE2Uc8mJjsfW6lxdkNsckeXg9bTsx1QjB+WK7/RW+JWYlzSKC3szH4oub2W54/PD7P8Kloa9Csh4sVIKBKtqp4VzfOCYVYovvquBlRGNh/8FkzzT84Ed13RqXXCJZ2oiZlgSUWTlmNo5QEozrryoZG14LdoGKAJFvg8MA5Gq5sEnVoOkC7QUW27m/Yalq9geatEdh5Wsl4UDw2dfevQoFLxo9qIvjHWG/OvpMd/pYAHGbYTJfaYRScHqW9LZFp+TPkKizz47LT8g7F2wx8asHKlVVeZ4/FIhRflG4z1/p4zO9OL6pTObROY06cqdmHW9cAGYtC0HIAYBGAFPBFIyUXZrSmVDOF+GJK/yvLuWV4/pjzDciAaPsf6HYov9e2M9yoV9DvbvmvcU2divooexWg8ANmtJQQtyQxbqWfhUEj4T80qQ20e4ca5Bc1nG7Q5m44zuKc=
    admin-user: AgBnFHabrA8ryPouCU/sref5cmL8teyVeiWP3+pTacZxY2U5e1LKwOakrJUpBln2/S9Lrsr2p27GMsvWpS4PbWubLdlqC6BvbCZA1tWa8XIR9CiBRI3VGjnAuRH2GkMU4C//B+Q6pAQ6dHlMjhJ0i48sBv5ZZqREcGtsjxU8ABaJfIGjpcV9KleH+tv/XhLAQg6pLXgNPMNcdchvQhock5fWmdt2UwYOmk63NUcAdZyxpoQrWR4aep6pkGKShFpsMz8x2Cw20yEvqq+yZhaVwU4BZY0FnUm8Ts24qKz0Tk4xedD+40w1T3Cey5qvGvYMxlkDRaq83ActLZ0WOL8Z3Wg55C57KeKMiGCMcKpBJbpNzblKsmBg8oCv65TTXF7oVzNQaetruLGJnGG1Xd/pPy//+OH5r8Npw+hxuGN9pfFccv8PZRlWUZx5Nfq7pdv77su9nq4Pl62kABqnAlLlZ21gzIg8qj5XrRfejKMSBVaffjfser1BuSvS2LLOiSeLEb0y0kqf0euFV/lZbP8ZVEoqYsfYvAFwAFmOX5QSMq/aB1eJ+qzK+qQlGQV/aUxcYYDiGY4TShAKJZwaEwOgSQdTZCk0OvB3TFZAx/DMcMxW6KPbPTnwn295/g1P1x2RI07+kRR+t2sgjfkWch6OIBy5ZbT3sCPS7sdLwyHBZbfMrDDzt1nistGWiueL8d5xgmoOXTHohw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
