"""Builds docs/reference/manifests.md: every manifest in the repo, plus the Helm chart rendered
with the GitOps values. Generated, so it cannot drift from what is deployed.

    python scripts/gen_manifest_reference.py
"""
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference" / "manifests.md"

SECTIONS = [
    ("Cluster bootstrap", "Kind topology and the Cilium values used before Argo CD exists.",
     ["cluster/kind-config.yaml", "cluster/cilium-values.yaml"]),
    ("Namespaces", "Pod Security labels per namespace.", ["gitops/platform/namespaces.yaml"]),
    ("Edge: Gateway API and TLS", "Issuers, the Envoy proxy settings, Gateway and routes.",
     ["gitops/edge/issuers.yaml", "gitops/edge/gateway.yaml"]),
    ("Data layer", "PostgreSQL (CloudNativePG), Redis and the backup schedule.",
     ["gitops/data/cnpg-cluster.yaml", "gitops/data/redis.yaml", "gitops/data/backup-schedule.yaml",
      "gitops/data/ledger-secrets.sealed.yaml"]),
    ("Backups", "Object store, bucket job and the Barman Cloud ObjectStore.",
     ["gitops/backup/seaweedfs.yaml", "gitops/backup/objectstore.yaml",
      "gitops/backup/seaweedfs-s3.sealed.yaml", "gitops/backup/s3-credentials-ledger.sealed.yaml",
      "gitops/backup/s3-credentials-storage.sealed.yaml", "gitops/platform/barman-plugin/kustomization.yaml"]),
    ("Network policies", "Default-deny plus one policy per allowed flow.",
     ["gitops/network-policies/ledger.yaml"]),
    ("Observability", "Scrape targets, alert rules, dashboard ConfigMap and Grafana credentials.",
     ["gitops/observability/monitors.yaml", "gitops/observability/alerts.yaml",
      "gitops/observability/grafana-admin.sealed.yaml"]),
    ("Platform Helm values", "Operators and the monitoring stack.",
     ["gitops/platform/argocd-values.yaml", "gitops/platform/sealed-secrets-values.yaml",
      "gitops/platform/cnpg-operator-values.yaml", "gitops/platform/kube-prometheus-stack-values.yaml",
      "gitops/platform/prometheus-adapter-values.yaml", "gitops/platform/metrics-server-values.yaml"]),
    ("Argo CD (GitOps)", "Project, root app-of-apps and every Application.",
     ["gitops/bootstrap/project.yaml", "gitops/bootstrap/root-app.yaml", "gitops/apps/platform.yaml",
      "gitops/apps/backup.yaml", "gitops/apps/workloads.yaml", "gitops/apps/monitoring.yaml"]),
    ("Helm chart values", "Defaults and the values Argo CD applies.",
     ["charts/ledgerflow/values.yaml", "charts/ledgerflow/values-gitops.yaml"]),
]

CIPHERTEXT = re.compile(r"\bAg[A-Za-z0-9+/=]{60,}")
OMIT_DASH = "(omitted: the dashboard is generated by `scripts/gen_dashboard.py`)"


def block(path: pathlib.Path, text: str) -> str:
    text = CIPHERTEXT.sub("<sealed ciphertext>", text.replace("\r\n", "\n")).rstrip()
    return f"### `{path.relative_to(ROOT).as_posix()}`\n\n```yaml\n{text}\n```\n"


def main() -> None:
    parts = [
        "# Manifest reference\n",
        "Generated by `scripts/gen_manifest_reference.py` from the files in this repository, so it "
        "matches what Argo CD deploys. Sealed Secret ciphertext is elided for readability. "
        "Do not edit by hand.\n",
        "| # | Section |\n|---|---|",
    ]
    names = [s[0] for s in SECTIONS] + ["Helm chart rendered with the GitOps values"]
    for i, name in enumerate(names, 1):
        anchor = re.sub(r"[^a-z0-9 -]", "", name.lower()).replace(" ", "-")
        parts.append(f"| {i} | [{name}](#{anchor}) |")
    parts.append("")

    for name, blurb, files in SECTIONS:
        parts.append(f"## {name}\n\n{blurb}\n")
        for rel in files:
            parts.append(block(ROOT / rel, (ROOT / rel).read_text()))

    rendered = subprocess.run(
        ["helm", "template", "ledgerflow", "charts/ledgerflow", "-n", "ledger",
         "-f", "charts/ledgerflow/values-gitops.yaml"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    parts.append(
        "## Helm chart rendered with the GitOps values\n\n"
        "Output of `helm template ledgerflow charts/ledgerflow -n ledger -f charts/ledgerflow/values-gitops.yaml`: "
        "exactly the objects the `ledgerflow` Argo CD application creates.\n\n"
        f"```yaml\n{rendered.rstrip()}\n```\n"
    )
    parts.append(f"## Grafana dashboard\n\n`gitops/observability/dashboard.yaml` {OMIT_DASH}.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
